### ISSUE TITLE
Feature Request: Panning in Plot

### ISSUE THREAD

**Issue by honggoff** [Sensirion/SmartGadget-Android#27]
Currently the history plot only supports 5 preset zoom levels and does not allow panning in the data. The preset zoom levels probably make sense, but it would be really helpful if I could look at old data in some more detail.

My proposal is to implement panning along the time axis and maybe in the y-axis as well, keeping the zoom levels constant.

I might start working on this, let me know if you are too.

**Comment by abrauchli** [comment]
Hey Honggoff, no we're not working on this but it sounds like a nice addition. PR is welcome.

**Comment by honggoff** [comment]
From what I can tell, the current version of androidplot has this feature. Unfortunately upgrading is not trivial, as the API changed quite a bit.

You can call me david, by the way.
