### ISSUE TITLE
Bug: Strange gaps when downloading logged data

### ISSUE THREAD

**Issue by honggoff** [Sensirion/SmartGadget-Android#31]
Both effects are observed with a logging interval of 10 minutes.

When downloading logged data, I reproducibly get a gap in the data as shown in the plot. I wiped the application data and then immediately performed a download. Can anyone reproduce this?
![screenshot_20160929-114216](https://cloud.githubusercontent.com/assets/140848/18949767/0535a862-863d-11e6-8b18-38954b93562b.png)
![screenshot_20160929-114225](https://cloud.githubusercontent.com/assets/140848/18949768/05362d1e-863d-11e6-8aff-fec4197d9094.png)

Also, for a logging interval of 10 minutes, the newest point is shown to be older than 10 minutes which cannot be. I assume there is an error in the timestamp calculation, so it might be a bug in libble.

![screenshot_20160929-114229](https://cloud.githubusercontent.com/assets/140848/18949769/05388d52-863d-11e6-9b91-8e0a4e5db23e.png)

When investigating the second issue, I found the documentation of the BLE protocol sorely missing. All I found is https://github.com/Sensirion/SmartGadget-Firmware/blob/master/Simple_BLE_Profile_Description.pdf . This lists the available characteristics, but does not explain their meaning and how you would use them when performing a download. Could you add more information to this? I am especially interested in the characteristics OldestTimestampMs, NewestTimestampMs and SyncTimeMs

**Comment by honggoff** [comment]
After debugging I found that the data points were lost before they were ever received by libble. Maybe my device is just too slow and cannot keep up with the download. The sequence numbers regularly have gaps of 4 points and sometimes up to 16 points.

**Comment by xavier-fernandez** [comment]
@honggoff Bluetooth does not guarantee that all packages are received by default, its connection principles are equivalent to the same ones as UDP for computer networks.

Since the the Smartgadgets do not support downloading the packages from a certain interval, I would consider downloading the entire gadget dataset twice, so missing datapoints will be downloaded then.

Very best regards :)

**Comment by Henning-Lenz** [comment]
I understand that BT doesn't guarantee, but even downloading the saved data multiple times seems to skip many datapoints. I'm currently testing with 1 min logging interval, so there should be a good visibility of missing points in the 10 min/1 hour views. The 1 hour view gets complete sometimes after multiple downloads, but I never managed to get the 10 min view complete within the 10 min it takes to roll over by itself...

**Comment by abrauchli** [comment]
@honggoff, @Henning-Lenz we did some fixes in that area in the last few releases. Is your issue still present in SmartGadget v1.8.7 or can we close this?

Thanks and kind regards,
Andreas
