### ISSUE TITLE
X-axis labels in plots unevenly distributed/missing values

### ISSUE THREAD

**Issue by Henning-Lenz** [Sensirion/SmartGadget-Android#35]
Running with 1 min of logging interval and live connection the X-axis labels in the 10 min view change while the screen is being updated. I would expect the view to show 10 to 0 constantly, but instead it displays

- 9  7  6 ... 0
- 8  7  6 ... 0
- 9  8  6 ... 0

in some unpredictable manner with each screen update. I could understand some update when the data is also scaled, but just the axis labels seem to change.

Within the "1 Hour" view labels are just unevenly distributed meaning distance is equal, but values are not equally spaced: 53  46  40  33  26  20  13  6  0 Perhaps the calculated distance is 6.5 min, but this is rounded in some way.

"6 Hours" and "1 Day" is going well, displaying 6 labels at the end of 6 intervals (1 hour/4 hours) and are always he same. One would expect the "1 hour" to be displaying 50  40  30  20  10  0 following that scheme, but strangely it is not.

The week view misses a whole day (today its Sunday, on Monday it was Friday), so always today-3 is not shown?! Additionally where "today" should be (right end of the screen) the display is always one day ahead (now: Thu but it is Wed - at least in my timezone ;-))

**Comment by abrauchli** [comment]
Hi Henning-Lenz

Thanks for reporting this. We noticed the unnatural behavior. We'll see if we can fix the plotting library but unfortunately it's not a priority right now. Patches are most welcome, though.

Let's keep this open until we can resolve it.

**Comment by Henning-Lenz** [comment]
Unfortunately I'm not into app development, so no patch suggestions from my side to expect.
If there was an export (see #28) I won't care much about strange plotting ;-)

**Comment by honggoff** [comment]
The app is using an ancient version of the androidplot library. They made a stable release in the meantime (1.2 actually). I tried upgrading once, but it is unfortunately a major undertaking because the API changed quite a bit.

**Comment by MBjoern** [comment]
We'll close these issues, as this repo is Deprecated and not maintained anymore.
