### ISSUE TITLE
Pairing happening with device - But data not updated

### ISSUE THREAD

**Issue by manumohannair** [Sensirion/SmartGadget-Android#37]
Hello,
I use AndroidStudio Version 2.2.2. I have a Nexus 6P and I am trying to read data with the app. Unfortunately I always get a blank readings screen. Any help here please ?

**Comment by abrauchli** [comment]
Hi, we could use some logcat output if you're using AndroidStudio anyway. Since it's old I'm marking this as closed, feel free to reopen.
