### ISSUE TITLE
Debugging code with Ulink2 and ST1

### ISSUE THREAD

**Issue by manumohannair** [Sensirion/SmartGadget-Android#40]
My Ulink2 debugger is not detecting the board. Could anyone help me here ?

**Comment by StTrow** [comment]
Hi manumohannair. Sure we can help. Did you connect the following pins to your debugger?
- SWDCLK (Pin 5 on the SmartHumiGadget connector ST1)
- SDWIO (Pin 3)
- 3V (Pin 6)
- GND (Pin 2)
You can find the schematics here:
https://github.com/Sensirion/SmartGadget-Hardware/blob/master/2214018_V4_Schematic.pdf

Please note that you will need to provide the 3V with an external power supply as the coin cell does not deliver sufficient power for the programming.

What kind of IDE do you use?

**Comment by abrauchli** [comment]
It looks like this thread concerns the board and not the android software. Marking as closed. Please reopen in https://github.com/Sensirion/SmartGadget-Firmware or https://github.com/Sensirion/SmartGadget-Hardware if this is still a concern.
