### ISSUE TITLE
 'Gradle sync failed' response 

### ISSUE THREAD

**Issue by JackFlash3** [Sensirion/SmartGadget-Android#42]
Hello Sensirion,

I was trying to load the GitHub project on Android Studio 2.3.3 and got the following message on my Log window:

**Gradle sync failed: Cause: org.gradle.api.internal.tasks.DefaultTaskInputs$TaskInputUnionFileCollection cannot be cast to org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection
			Consult IDE log for more details (Help | Show Log)**

Do you have any idea what could cause this failure?

thanks a lot

**Comment by JackFlash3** [comment]
Ok,

Problem solved, My build gradle version was old.

tnx

**Comment by abrauchli** [comment]
Hi @JackFlash3, thanks for your interest and especially for letting us know about what fixed your issue. Marking topic as closed.

Cheers
