### ISSUE TITLE
Gradle Sync failed in Android SDK version 3.1 Gradle version 4.4

### ISSUE THREAD

**Issue by saule** [Sensirion/SmartGadget-Android#47]
Hello,
My android Studio version is 3.1
Gradle version is 4.4.
Gradle project sync failed.
the message is 

> The versions of the Android Gradle plugin and Gradle are not compatible.
Please do one of the following:<ul><li>Update your plugin to version 2.4. This will require changes to build.gradle due to API changes.
Open migration guide</li><li>Downgrade Gradle to version 3.5.
Fix Gradle wrapper and re-import project</li></ul>

I had to do some changes in order to succeed to Sync gradle.

**Comment by MBjoern** [comment]
We'll close these issues, as this repo is Deprecated and not maintained anymore.
