### ISSUE TITLE
App keep Asking for bluetooth connection even if refusing

### ISSUE THREAD

**Issue by ahmedmaz24** [Sensirion/SmartGadget-Android#49]
The app keeps asking to bluetooth connect even if you press " refuse "

**Comment by chjaeggi** [comment]
Hi [ahmedmaz24](/ahmedmaz24),

Where do these requests pop up? What is your intention with the app (by refusing the permission)?
Did you see our newer app MyAmbience?

https://play.google.com/store/apps/details?id=com.sensirion.myambience 

Maybe it serves your purpose better.

Cheers,
Christian

**Comment by ahmedmaz24** [comment]
Hi,This is app was my first contact with the open source project community so I was testing how to make an issue and all 


Sent from Yahoo Mail for iPhone


On Friday, February 22, 2019, 8:03 AM, Christian Jaeggi <notifications@github.com> wrote:


Hi ahmedmaz24,

Where do these requests pop up? What is your intention with the app (by refusing the permission)?
Did you see our newer app MyAmbience?

https://play.google.com/store/apps/details?id=com.sensirion.myambience

Maybe it serves your purpose better.

Cheers,
Christian

**Comment by MBjoern** [comment]
We'll close these issues, as this repo is Deprecated and not maintained anymore.
