### ISSUE TITLE
the menu navigation tab is not present in emulators

### ISSUE THREAD

**Issue by ahmedmaz24** [Sensirion/SmartGadget-Android#50]
in order to get to the menu i have to randomly press on the screen and i hope there will be a menu icon on the side for better user experience

**Comment by chjaeggi** [comment]
Hi [ahmedmaz24](/ahmedmaz24),

What do you mean by 'get to the menu'? Do you see the navigation menu in the bottom of the app or do you have to press randomly on the screen somewhere for it to appear?

Cheers,
Christian

**Comment by ahmedmaz24** [comment]
i'm sorry but truns out the app doesn't have a menu when its opened in a emulator

**Comment by MBjoern** [comment]
We'll close these issues, as this repo is Deprecated and not maintained anymore.
